services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: sail_db_testing
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p12345678"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - internal

  main-app:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  service-a:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      reverb:
        condition: service_started

  service-b-queue:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      reverb:
        condition: service_started

  reverb:
    depends_on:
      redis:
        condition: service_started
